---
version: 0.2

phases:
  build:
    commands:
      - echo Build started 
      - echo Compiling the Python code
  post_build:
    commands:
      - echo Build completed on date
artifacts:
  files:
    - remove_snapshots.py 
